@echo off
echo 🚀 Starting Blog App with Public Access...
echo 🌐 Chrome will open automatically...
echo 📱 QR code will be generated for mobile access...
echo.
python run_public.py
echo.
echo 🛑 App stopped. Press any key to exit...
pause